account/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

post/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'post'

urlpatterns = [
    path('all/', post_index, name='index'),
    path('create/', post_create, name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    re_path(r'^(?P<id>\d+)/edit/$', post_edit, name='edit'),
    re_path(r'^(?P<id>\d+)/delete/$', post_delete, name='delete'),
]

windru/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_view, name='home'),
    path('post/', include('post.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, HttpResponse

def home_view(request):

    if request.user.is_authenticated:
        context = {
            'name': request.user
        }
    else:
        context = {
            'name': 'Anonymous User' 
        }
    
    return render(request, 'home.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}Django Blog{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>

    {% include 'header.html' %}
    
    <div class="container">
        <div class="row">
            {% include 'messages.html' %}

            {% block body %}

            {% endblock body %}
        </div>
    </div>
    
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-default" role="banner">
    <div class="container">

        <div class="navbar-header">

            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="{% url 'home' %}" class="navbar-brand">Django Blog</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Search">
                    </span>
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}">Add a New Post</a></li>
                {% endif %}
                <li><a href="{% url 'post:index' %}">Blog</a></li>
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'account:register' %}">Register</a></li>
                    <li><a href="{% url 'account:login' %}">Login</a></li>
                {% else %}
                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                {% endif %}
            </ul>
            

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title%}Home | {{ block.super }}{% endblock title%}

{% block body %}

	<div class="container">Hello {{ name }}</div>

{% endblock body %}

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert {% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}
    </ul>
{% endif %}